"use client";

import dynamic from "next/dynamic";
import { useEffect, useState } from "react";
import { asset } from "@/lib/utils";

const HeroField = dynamic(() => import("./HeroField"), { ssr: false });

function canUseWebGL() {
  try {
    const c = document.createElement("canvas");
    return Boolean(c.getContext("webgl2") || c.getContext("webgl"));
  } catch {
    return false;
  }
}

/**
 * Always renders the static SVG field (instant, zero JavaScript). On larger
 * screens with a mouse, WebGL and motion allowed, three.js is downloaded only
 * after the first mouse movement (or 3 s), then fades in over the SVG.
 */
export function HeroVisual() {
  const [load, setLoad] = useState(false);
  const [ready, setReady] = useState(false);

  useEffect(() => {
    const ok =
      window.matchMedia("(min-width: 768px) and (pointer: fine)").matches &&
      !window.matchMedia("(prefers-reduced-motion: reduce)").matches &&
      canUseWebGL();
    if (!ok) return;
    const go = () => setLoad(true);
    const timer = window.setTimeout(go, 3000);
    window.addEventListener("pointermove", go, { once: true, passive: true });
    return () => {
      window.clearTimeout(timer);
      window.removeEventListener("pointermove", go);
    };
  }, []);

  return (
    <div
      aria-hidden
      className="pointer-events-none absolute inset-0 [mask-image:linear-gradient(to_bottom,transparent,#000_30%,#000_80%,transparent)]"
    >
      <div
        className={
          "absolute inset-0 transition-opacity duration-1000 " +
          (ready ? "opacity-0" : "opacity-100")
        }
      >
        <FieldFallback />
      </div>
      {load && (
        <div
          className={
            "absolute inset-0 transition-opacity duration-1000 " +
            (ready ? "opacity-100" : "opacity-0")
          }
        >
          <HeroField onReady={() => setReady(true)} />
        </div>
      )}
    </div>
  );
}

/**
 * Static first paint: two pre-drawn SVG images (one per theme, generated by
 * scripts/generate-field.mjs). One image decode instead of hundreds of DOM nodes.
 */
function FieldFallback() {
  return (
    <>
      {/* eslint-disable @next/next/no-img-element */}
      <img
        src={asset("/field-light.svg")}
        alt=""
        width={1000}
        height={1000}
        decoding="async"
        className="size-full object-cover dark:hidden"
      />
      <img
        src={asset("/field-dark.svg")}
        alt=""
        width={1000}
        height={1000}
        decoding="async"
        className="hidden size-full object-cover dark:block"
      />
    </>
  );
}
